spring.mail.host: smtp.qq.com
spring.mail.username: 529540465@qq.com
spring.mail.password: lidsypnbufolbgga

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true